main: StartMenu.cpp StructDefine.cpp TimeShow.cpp pch.cpp ConverStr.cpp pch.h StructDefine.h 
	g++ -std=c++11 -o main  StartMenu.cpp StructDefine.cpp TimeShow.cpp pch.cpp ConverStr.cpp pch.h StructDefine.h
